name: deploy

on:
  workflow_call:
    secrets:
      github_checkout_token:
        required: true
      gcr_token:
        required: true
      npm_token:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      image-tags: ${{ steps.docker_meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v3
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: |
            gcr.io/fabric-registry/cloud-services/${{ github.event.repository.name }}
          flavor: |
            latest=true
          tags: |
            type=sha
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.gcr_token }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            NPM_TOKEN=${{ secrets.npm_token }}
      - run: echo ${{ steps.docker_build.outputs.digest }}

  update-image:
    runs-on: ubuntu-latest
    needs:
      - docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.github_checkout_token }}
      - name: Get tag
        id: get-tag
        run: |
          TAG=$(echo ${{toJSON(needs.docker.outputs.image-tags)}} | cut -d ":" -f 2 | cut -d "\\" -f 1 )
          echo $TAG
          echo "::set-output name=tag::$TAG"
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.30.2
        with:
          cmd: yq eval -i '.fabric-chart.image.tag = "${{steps.get-tag.outputs.tag}}"' deployment/values.yaml
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'deploy image ${{steps.get-tag.outputs.tag}}'
          default_author: github_actions
