name: lint

on:
  workflow_call:
    secrets:
      npm_token:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com
      - run: yarn
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}
      - run: yarn lint
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}
