name: publish-package

on:
  workflow_call:
    inputs:
      yarn_build_script:
        required: true
        type: string
      package_path:
        required: true
        type: string
    secrets:
      github_token:
        required: true
      npm_token:
        required: true

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: yarn
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}
      - run: yarn ${{ inputs.yarn_build_script }}
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}
      - run: npm publish
        working-directory: ${{ inputs.package_path }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.github_token }}
          NPM_TOKEN: ${{ secrets.npm_token }}
